language: generic
osx_image: xcode9

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- swift package generate-xcodeproj --enable-code-coverage
- sh Scripts/launch_tests.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
